package goframe

import (
	"context"
	"errors"
	"os"
	"testing"

	"github.com/gogf/gf/v2/database/gdb"
)

// Launched by TestLocalSignedCoreKVInterop with an ephemeral signed Core.
// It uses GoFrame's public gdb API, rather than the driver's fake native DB.
func TestLocalSignedCoreGoFrameInterop(t *testing.T) {
	path := os.Getenv("TALON_GOFRAME_LIVE_DB")
	if path == "" {
		t.Skip("run through the local signed Core integration fixture")
	}
	ctx := context.Background()
	db, err := gdb.New(gdb.ConfigNode{Type: DriverName, Name: path})
	if err != nil {
		t.Fatal(err)
	}
	if _, err := db.Exec(ctx, "CREATE TABLE gf_live (id INT PRIMARY KEY, name TEXT)"); err != nil {
		for cause := err; cause != nil; cause = errors.Unwrap(cause) {
			t.Logf("create error: %v", cause)
		}
		t.Fatalf("create: %v", err)
	}
	if result, err := db.Exec(ctx, "INSERT INTO gf_live (id, name) VALUES (?, ?)", 1, "first"); err != nil {
		t.Fatalf("insert: %v", err)
	} else if count, err := result.RowsAffected(); err != nil || count != 1 {
		t.Fatalf("insert affected=%d, %v", count, err)
	}
	row, err := db.GetOne(ctx, "SELECT id, name FROM gf_live WHERE id = ?", 1)
	if err != nil || row["name"].String() != "first" {
		t.Fatalf("query row=%v, %v", row, err)
	}
	type item struct {
		ID   int    `orm:"id"`
		Name string `orm:"name"`
	}
	if _, err := db.Model("gf_live").Ctx(ctx).Save(item{ID: 1, Name: "saved"}); err != nil {
		t.Fatalf("model save: %v", err)
	}
	row, err = db.GetOne(ctx, "SELECT name FROM gf_live WHERE id = ?", 1)
	if err != nil || row["name"].String() != "saved" {
		t.Fatalf("saved row=%v, %v", row, err)
	}
	if result, err := db.Model("gf_live").Ctx(ctx).Where("id", 1).Update(struct {
		Name string `orm:"name"`
	}{Name: "updated"}); err != nil {
		t.Fatalf("model update: %v", err)
	} else if count, err := result.RowsAffected(); err != nil || count != 1 {
		t.Fatalf("model update affected=%d, %v", count, err)
	}
	row, err = db.Model("gf_live").Ctx(ctx).Where("id", 1).One()
	if err != nil || row["name"].String() != "updated" {
		t.Fatalf("model one=%v, %v", row, err)
	}
	fields, err := db.TableFields(ctx, "gf_live")
	if err != nil || fields["id"] == nil || fields["id"].Key != "PRI" {
		t.Fatalf("table fields=%v, %v", fields, err)
	}
	tables, err := db.Tables(ctx)
	if err != nil {
		t.Fatalf("tables: %v", err)
	}
	found := false
	for _, table := range tables {
		found = found || table == "gf_live"
	}
	if !found {
		t.Fatalf("gf_live absent from tables: %v", tables)
	}
	tx, err := db.Begin(ctx)
	if err != nil {
		t.Fatalf("begin: %v", err)
	}
	if _, err := tx.Exec("INSERT INTO gf_live (id, name) VALUES (?, ?)", 2, "rollback"); err != nil {
		t.Fatalf("transaction insert: %v", err)
	}
	if err := tx.Rollback(); err != nil {
		t.Fatalf("rollback: %v", err)
	}
	row, err = db.GetOne(ctx, "SELECT id FROM gf_live WHERE id = ?", 2)
	if err != nil || len(row) != 0 {
		t.Fatalf("rolled-back row=%v, %v", row, err)
	}

	// Exercise SQL generated by GoFrame v2.8.3 rather than only handwritten
	// statements. Core SQL unit tests alone cannot establish driver coverage.
	if _, err := db.Exec(ctx, "CREATE TABLE gf_sql_groups (id INT PRIMARY KEY, label TEXT)"); err != nil {
		t.Fatalf("create groups: %v", err)
	}
	if _, err := db.Exec(ctx, "CREATE TABLE gf_sql_items (id INT PRIMARY KEY, group_id INT, name TEXT, score INT)"); err != nil {
		t.Fatalf("create items: %v", err)
	}
	type group struct {
		ID    int    `orm:"id"`
		Label string `orm:"label"`
	}
	type scoredItem struct {
		ID      int    `orm:"id"`
		GroupID int    `orm:"group_id"`
		Name    string `orm:"name"`
		Score   int    `orm:"score"`
	}
	for _, value := range []group{{1, "one"}, {2, "two"}} {
		if _, err := db.Model("gf_sql_groups").Ctx(ctx).Insert(value); err != nil {
			t.Fatalf("model insert group: %v", err)
		}
	}
	for _, value := range []scoredItem{{1, 1, "alpha", 10}, {2, 1, "beta", 20}, {3, 2, "gamma", 30}} {
		if _, err := db.Model("gf_sql_items").Ctx(ctx).Insert(value); err != nil {
			t.Fatalf("model insert item: %v", err)
		}
	}
	if _, err := db.Exec(ctx, "CREATE INDEX gf_sql_items_group ON gf_sql_items (group_id)"); err != nil {
		t.Fatalf("create group index: %v", err)
	}
	if count, err := db.Model("gf_sql_items").Ctx(ctx).Where("group_id", 1).Count(); err != nil || count != 2 {
		t.Fatalf("indexed equality count=%d, %v", count, err)
	}
	if _, err := db.Exec(ctx, "CREATE TABLE gf_sql_batch (id INT PRIMARY KEY, group_id INT, name TEXT, score INT)"); err != nil {
		t.Fatalf("create batch table: %v", err)
	}
	if _, err := db.Model("gf_sql_batch").Ctx(ctx).Insert([]scoredItem{{4, 1, "delta", 40}, {5, 2, "epsilon", 50}}); err != nil {
		t.Fatalf("model batch insert: %v", err)
	}
	if count, err := db.Model("gf_sql_batch").Ctx(ctx).Count(); err != nil || count != 2 {
		t.Fatalf("model batch insert count=%d, %v", count, err)
	}
	page, err := db.Model("gf_sql_items").Ctx(ctx).WhereIn("id", []int{1, 3}).OrderDesc("id").Page(1, 2).All()
	if err != nil || len(page) != 2 || page[0]["id"].Int() != 3 || page[1]["id"].Int() != 1 {
		t.Fatalf("model IN/order/page=%v, %v", page, err)
	}
	page, total, err := db.Model("gf_sql_items").Ctx(ctx).Order("id").Page(1, 2).AllAndCount(false)
	if err != nil || total != 3 || len(page) != 2 || page[0]["id"].Int() != 1 {
		t.Fatalf("model AllAndCount page=%v total=%d, %v", page, total, err)
	}
	page, err = db.Model("gf_sql_items").Ctx(ctx).Order("id").Page(2, 2).All()
	if err != nil || len(page) != 1 || page[0]["id"].Int() != 3 {
		t.Fatalf("model offset page=%v, %v", page, err)
	}
	distinct, err := db.Model("gf_sql_items").Ctx(ctx).Fields("group_id").Distinct().Order("group_id").All()
	if err != nil || len(distinct) != 2 || distinct[0]["group_id"].Int() != 1 || distinct[1]["group_id"].Int() != 2 {
		t.Fatalf("model DISTINCT=%v, %v", distinct, err)
	}
	filtered, err := db.Model("gf_sql_items").Ctx(ctx).WhereBetween("score", 10, 20).WhereLike("name", "%a%").Count()
	if err != nil || filtered != 2 {
		t.Fatalf("model BETWEEN/LIKE/count=%d, %v", filtered, err)
	}
	filtered, err = db.Model("gf_sql_items").Ctx(ctx).Where("score < ?", 15).WhereOr("score > ?", 25).Count()
	if err != nil || filtered != 2 {
		t.Fatalf("model OR/count=%d, %v", filtered, err)
	}
	if _, err := db.Exec(ctx, "CREATE TABLE gf_sql_nulls (id INT PRIMARY KEY, note TEXT)"); err != nil {
		t.Fatalf("create nullable table: %v", err)
	}
	if _, err := db.Exec(ctx, "INSERT INTO gf_sql_nulls VALUES (1, NULL), (2, 'present')"); err != nil {
		t.Fatalf("insert nullable rows: %v", err)
	}
	if count, err := db.Model("gf_sql_nulls").Ctx(ctx).WhereNull("note").Count(); err != nil || count != 1 {
		t.Fatalf("model IS NULL count=%d, %v", count, err)
	}
	if count, err := db.Model("gf_sql_nulls").Ctx(ctx).WhereNotNull("note").Count(); err != nil || count != 1 {
		t.Fatalf("model IS NOT NULL count=%d, %v", count, err)
	}
	joined, err := db.Model("gf_sql_items", "i").Ctx(ctx).
		LeftJoin("gf_sql_groups", "g", "i.group_id=g.id").
		Fields("i.id, g.label").Order("i.id").All()
	if err != nil || len(joined) != 3 || joined[0]["label"].String() != "one" || joined[2]["label"].String() != "two" {
		t.Fatalf("model LEFT JOIN=%v, %v", joined, err)
	}
	joined, err = db.Model("gf_sql_items", "i").Ctx(ctx).
		InnerJoin("gf_sql_groups", "g", "i.group_id=g.id").
		Fields("i.id, g.label").Where("g.label", "one").Order("i.id").All()
	if err != nil || len(joined) != 2 || joined[0]["id"].Int() != 1 || joined[1]["id"].Int() != 2 {
		t.Fatalf("model INNER JOIN=%v, %v", joined, err)
	}
	if count, err := db.Model("gf_sql_items").Ctx(ctx).
		Where("group_id IN (SELECT id FROM gf_sql_groups WHERE label = ?)", "one").Count(); err != nil || count != 2 {
		t.Fatalf("model IN subquery count=%d, %v", count, err)
	}
	grouped, err := db.Model("gf_sql_items").Ctx(ctx).
		Fields("group_id, COUNT(*) AS n").Group("group_id").Having("COUNT(*) > ?", 1).
		Order("group_id").All()
	if err != nil || len(grouped) != 1 || grouped[0]["group_id"].Int() != 1 || grouped[0]["n"].Int() != 2 {
		t.Fatalf("model GROUP BY/HAVING=%v, %v", grouped, err)
	}
	sum, err := db.Model("gf_sql_items").Ctx(ctx).Sum("score")
	if err != nil || sum != 60 {
		t.Fatalf("model SUM=%v, %v", sum, err)
	}
	avg, err := db.Model("gf_sql_items").Ctx(ctx).Avg("score")
	if err != nil || avg != 20 {
		t.Fatalf("model AVG=%v, %v", avg, err)
	}
	min, err := db.Model("gf_sql_items").Ctx(ctx).Min("score")
	if err != nil || min != 10 {
		t.Fatalf("model MIN=%v, %v", min, err)
	}
	max, err := db.Model("gf_sql_items").Ctx(ctx).Max("score")
	if err != nil || max != 30 {
		t.Fatalf("model MAX=%v, %v", max, err)
	}
	if _, err := db.Exec(ctx, "CREATE TABLE gf_sql_money (id INT PRIMARY KEY, amount DECIMAL(18,2))"); err != nil {
		t.Fatalf("create decimal table: %v", err)
	}
	if _, err := db.Exec(ctx, "INSERT INTO gf_sql_money (id, amount) VALUES (?, ?)", 1, "1234567890123456.78"); err != nil {
		t.Fatalf("insert exact decimal: %v", err)
	}
	money, err := db.Model("gf_sql_money").Ctx(ctx).Where("id", 1).One()
	if err != nil || money["amount"].String() != "1234567890123456.78" {
		t.Fatalf("exact decimal=%v, %v", money, err)
	}
	if result, err := db.Model("gf_sql_items").Ctx(ctx).InsertIgnore(scoredItem{1, 1, "changed", 99}); err != nil {
		t.Fatalf("model InsertIgnore: %v", err)
	} else if affected, err := result.RowsAffected(); err != nil || affected != 0 {
		t.Fatalf("model InsertIgnore affected=%d, %v", affected, err)
	}
	unchanged, err := db.Model("gf_sql_items").Ctx(ctx).Where("id", 1).One()
	if err != nil || unchanged["name"].String() != "alpha" {
		t.Fatalf("InsertIgnore changed existing row=%v, %v", unchanged, err)
	}
	if result, err := db.Model("gf_sql_items").Ctx(ctx).Where("id", 3).Delete(); err != nil {
		t.Fatalf("model delete: %v", err)
	} else if affected, err := result.RowsAffected(); err != nil || affected != 1 {
		t.Fatalf("model delete affected=%d, %v", affected, err)
	}
	if count, err := db.Model("gf_sql_items").Ctx(ctx).Count(); err != nil || count != 2 {
		t.Fatalf("count after delete=%d, %v", count, err)
	}
	tx, err = db.Begin(ctx)
	if err != nil {
		t.Fatalf("commit begin: %v", err)
	}
	if _, err := tx.Exec("INSERT INTO gf_sql_items (id, group_id, name, score) VALUES (?, ?, ?, ?)", 4, 2, "delta", 40); err != nil {
		t.Fatalf("commit insert: %v", err)
	}
	if err := tx.Commit(); err != nil {
		t.Fatalf("commit: %v", err)
	}
	if count, err := db.Model("gf_sql_items").Ctx(ctx).Where("id", 4).Count(); err != nil || count != 1 {
		t.Fatalf("committed row count=%d, %v", count, err)
	}
}
